export const cafeData = [
  {
    id: 1,
    name: "1번 카페",
    adress: "서울특별시 강남구 강남로 1",
    phone: "02-000-0001",
    tags: ["분위기 좋은", "카공"],
    menu: [
      { name: "아메리카노", price: "5000원" },
      { name: "카페라떼", price: "5000원" },
      { name: "카푸치노", price: "5000원" },
      { name: "카라멜마끼야또", price: "5000원" },
      { name: "카페모카", price: "5000원" },
      { name: "자몽티", price: "5000원" },
      { name: "페퍼민트티", price: "5000원" },
      { name: "캐모마일티", price: "5000원" },
      { name: "핫초코", price: "5000원" },
    ],
  },
  {
    id: 2,
    name: "2번 카페",
    adress: "서울특별시 강남구 강남로 2",
    phone: "02-000-0002",
    tags: ["조용한", "카공"],
    menu: [
      { name: "아메리카노", price: "5000원" },
      { name: "카페라떼", price: "5000원" },
      { name: "카푸치노", price: "5000원" },
      { name: "카라멜마끼야또", price: "5000원" },
      { name: "카페모카", price: "5000원" },
      { name: "자몽티", price: "5000원" },
      { name: "페퍼민트티", price: "5000원" },
      { name: "캐모마일티", price: "5000원" },
      { name: "핫초코", price: "5000원" },
    ],
  },
  {
    id: 3,
    name: "3번 카페",
    adress: "서울특별시 강남구 강남로 3",
    phone: "02-000-0003",
    tags: ["힙한", "카공"],
    menu: [
      { name: "아메리카노", price: "5000원" },
      { name: "카페라떼", price: "5000원" },
      { name: "카푸치노", price: "5000원" },
      { name: "카라멜마끼야또", price: "5000원" },
      { name: "카페모카", price: "5000원" },
      { name: "자몽티", price: "5000원" },
      { name: "페퍼민트티", price: "5000원" },
      { name: "캐모마일티", price: "5000원" },
      { name: "핫초코", price: "5000원" },
    ],
  },
  {
    id: 4,
    name: "4번 카페",
    adress: "서울특별시 강남구 강남로 4",
    phone: "02-000-0004",
    tags: ["앤틱한", "카공"],
    menu: [
      { name: "아메리카노", price: "5000원" },
      { name: "카페라떼", price: "5000원" },
      { name: "카푸치노", price: "5000원" },
      { name: "카라멜마끼야또", price: "5000원" },
      { name: "카페모카", price: "5000원" },
      { name: "자몽티", price: "5000원" },
      { name: "페퍼민트티", price: "5000원" },
      { name: "캐모마일티", price: "5000원" },
      { name: "핫초코", price: "5000원" },
    ],
  },
  {
    id: 5,
    name: "5번 카페",
    adress: "서울특별시 강남구 강남로 5",
    phone: "02-000-0005",
    tags: ["스타일리시한", "카공"],
    menu: [
      { name: "아메리카노", price: "5000원" },
      { name: "카페라떼", price: "5000원" },
      { name: "카푸치노", price: "5000원" },
      { name: "카라멜마끼야또", price: "5000원" },
      { name: "카페모카", price: "5000원" },
      { name: "자몽티", price: "5000원" },
      { name: "페퍼민트티", price: "5000원" },
      { name: "캐모마일티", price: "5000원" },
      { name: "핫초코", price: "5000원" },
    ],
  },
  {
    id: 6,
    name: "6번 카페",
    adress: "서울특별시 강남구 강남로 6",
    phone: "02-000-0006",
    tags: ["모던한", "카공"],
    menu: [
      { name: "아메리카노", price: "5000원" },
      { name: "카페라떼", price: "5000원" },
      { name: "카푸치노", price: "5000원" },
      { name: "카라멜마끼야또", price: "5000원" },
      { name: "카페모카", price: "5000원" },
      { name: "자몽티", price: "5000원" },
      { name: "페퍼민트티", price: "5000원" },
      { name: "캐모마일티", price: "5000원" },
      { name: "핫초코", price: "5000원" },
    ],
  },
];
